# Generated by Django 6.0.5 on 2026-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='booked_seats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='train',
            name='classes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='train',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='train',
            name='fare',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='train',
            name='from_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='train',
            name='to_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.CharField(max_length=10),
        ),
    ]
