# Generated by Django 6.0.5 on 2026-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_booked_seats_train_classes_train_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='train',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='train',
            name='seat_gender',
            field=models.JSONField(default=dict),
        ),
    ]
